remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Chloe Graham-Major's Portfolio
Description: Engineering portfolio featuring work in power markets, energy networks, renewable energy, battery storage, data analytics, and electronic design.
